#!/bin/tcsh -f

# Create ACF_values.1D file that contains ACF values for each subject 
# from errts-file using subject-specific full_mask as Mask file. 

set subjects = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40"
 
foreach s ( $subjects )

echo "This is Subject nr." ${s}  >> Values.1D
3dFWHMx -mask full_mask.tshift_outliers_removed_5mm_smoothed${s}+tlrc -detrend -ACF -input errts.tshift_outliers_removed_5mm_smoothed${s}_REML+tlrc >> ACF_values.1D

end



